version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rails8demo_postgres
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: rails8_demo_development
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: rails8demo_web
    ports:
      - "3000:3000"
    volumes:
      - .:/app/Rails8demo
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: local_user
      DATABASE_PASSWORD: admin@123
      DATABASE_NAME: rails8_demo_development
    depends_on:
      - db

volumes:
  pg_data:
